---
- name: create lambda function
  hosts: localhost
  gather_facts: yes
  vars_files:
      - secrets.yml
  tasks:
      - name: creating lambda function
        lambda:
              name: function_to_test_the_code
              aws_access_key: "{{ aws_access_key }}"
              aws_secret_key: "{{ aws_secret_key }}"
              aws_region: "{{ aws_region }}"
              handler: Classification.lambda_handler
              role: "arn:aws:iam::046131509106:role/lambda_role"
              runtime: "python3.8"
              state: present
              zip_file: "all_files.zip"
      
