---
- name: "create s3 bucket"
  hosts: localhost
  gather_facts: yes
  vars_files:
    - secrets.yml
  connection: local
  tasks:
  - name: creating s3 bucket
    s3_bucket:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "ap-south-1"
      name: "docexam"
      state: present
  - name: Simple PUT operation
    s3_bucket:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "ap-south-1"
      bucket: mybucket
      object: all_files.zip
      src: all_files.zip
      mode: put

